Sinthros/madden-franchise-utils

.gitignore
EXE files will not be tracked anymore.
=> Updated gitignore to ignore EXEs

6teamPlayoffM24/6teamPlayoffM24.js
The 6 team playoff tool now utilizes FranchiseUtils.
=> Updated 6 team playoff tool to use FranchiseUtils

presentationIdFix/buildExe.bat, presentationIdFix/presentationIdFix.js
Added the source for the presentation ID fix tool and batch script to build exe.
=> Added presentation ID fix tool

presentationIdFix/buildExe.bat, presentationIdFix/presentationIdFix.js, sixTeamPlayoffM24/buildExe.bat, sixTeamPlayoffM24/sixTeamPlayoffM24.js
Updated table references in six team and ID fix script to utilize new table reference file.
=> Updated six team and ID fix table references

selectWeatherM24/buildExe.bat, selectWeatherM24/selectWeatherM24.js
Added tool to select weather in franchise games.
=> Added select weather tool

selectWeatherM24/selectWeatherM24.js
Updates for the weather selector tool:
- Fixed an issue with one of the randomized wind options
- Fixed an issue with clear weather not always applying
- Added two new weather choices: **Overcast (Cold)** and **Overcast (Warm)**
=> Weather Tool Update

randomizeDraftClassEquipmentM24/buildExe.bat, randomizeDraftClassEquipmentM24/lookupFiles/all_asset_names.json, randomizeDraftClassEquipmentM24/randomizeDraftClassEquipmentM24.js
Added tool that randomizes draft class equipment based on active player gear.
=> Added draft class equipment randomizer

randomizeDraftClassEquipmentM24/randomizeDraftClassEquipmentM24.js
Removed some unnecessary code and added a couple more comments
=> Cleaned up code for equipment tool

.gitignore
Files for VIsual Studio will now be ignored.
=> Updated gitignore to ignore Visual Studio setup files

retroSchedules/transferRetroSchedule.js, retroSchedules/transferScheduleFromJson.js
- Added an option in the retro schedule tool for the user to provide a custom JSON by entering 0 at the year prompt.
- Fixed an issue with the too many games in JSON error not exiting and printing a false success message.
=> JSON schedule tool changes

scheduleExtractorM24/scheduleExtractorM24.js
Added a sorter that sorts games chronologically before writing the JSON to file.
=> Schedule Extractor - Added chronological game sort

selectWeatherM24/selectWeatherM24.js
Added support for opening/closing roofs in hybrid stadiums.
=> Weather Selector - Added support for hybrid roofs

selectWeatherM24/selectWeatherM24.js
- Added the option for custom temperatures with each weather option
- Updated the hybrid roof feature to display only closed roof and open roof as options if the roof is currently closed.
=> Weather Selector - Custom temperature selection & closed roof update

presentationIdFix/lookupFiles/WiiMaster2015.json, presentationIdFix/lookupFiles/WiiMaster2017.json
Updated the list of override assetnames for the presentation ID fix tool.
=> Presentation ID Fix - Updated override assetname list

maddenSynth/.gitignore, maddenSynth/lookupFiles/injuryTypes.json, maddenSynth/maddenSynth.js, maddenSynth/miscDevelopmentFiles/injuryenum.json
Added the initial alpha version of MaddenSynth, a tool for creating and generating franchise scenarios.
**NOTE:** This is still a very early version so there are many features that don't work yet. Currently the only thing that is implemented is creating and generating injury scenarios.
=> MaddenSynth - Initial alpha version of scenario tool

maddenSynth/lookupFiles/allPositions.json, maddenSynth/lookupFiles/ratingTypes.json, maddenSynth/maddenSynth.js
Includes several changes for beta 0.2:
- The user can now generate multiple scenarios in one generation
- Morale and weight are now editable ratings
- Injury scenarios can now filter by position group
- The user can now build a custom list of positions for a position group
=> MaddenSynth - Changes for beta 0.2

maddenSynth/README.txt, maddenSynth/maddenSynth.js
Changes:
- Fixed an issue that would allow for users to input invalid numbers when choosing a number of scenarios to generate
- Added the ability to set random thresholds when creating scenarios
- Added the ability to set player selection parameters when creating scenarios
- Added a new get random player function that abides by selection parameters
- Removed some garbage code that was left over
- Updated README to explain new random threshold
=> MaddenSynth - Beta 0.3 Changes

draftPickReset/buildExe.bat, draftPickReset/draftPickReset.js
Added tool to restore all draft picks to their original teams
=> Added draft pick reset tool

presentationIdFix/lookupFiles/WiiMaster2015.json, presentationIdFix/lookupFiles/WiiMaster2017.json, presentationIdFix/presentationIdFix.js
Added some more assetname overrides, and also added messaging related to the progression tool.
=> Presentation ID Fix - Updated override assetname lookups and added progression tool messaging

assignVanityGear/assignVanityGear.js, assignVanityGear/buildExe.bat, assignVanityGear/buildExeDev.bat, assignVanityGear/lookupFiles/vanityGearLookup.json
Added tool that assigns vanity gear to all players
=> Added vanity gear mass assignment tool

maddenSynth/maddenSynth.js
- Cleaned up code for MaddenSynth with several comments throughout the program and fixed some convention related issues
- Added game year validation
- Removed some variables that were not being used
=> MaddenSynth - Code cleanup + some fixes

presentationIdFix/presentationIdFix.js, randomizeDraftClassEquipmentM24/randomizeDraftClassEquipmentM24.js
Presentation ID Fix:
- Used game year enum for year check
Draft Class Equipment Randomizer:
- Converted player enumeration to a separate function
- Passed in tables as parameters to a couple functions
=> Presentation ID Fix & Draft Class Equipment Randomizer - Cleanup + minor changes

assignVanityGear/assignVanityGear.js, maddenSynth/maddenSynth.js, randomizeDraftClassEquipmentM24/randomizeDraftClassEquipmentM24.js, selectWeatherM24/selectWeatherM24.js
MaddenSynth:
- Improved documentation
Assign Vanity Gear:
- Improved documentation
Weather Selector:
- Using new method of getting tables object
Draft Class Equipment Randomizer:
- Using new method of getting tables object
=> Documentation and table object updates

draftPickReset/draftPickReset.js, draftPlayerImportNcaa/draftPlayerImportNcaa.js, maddenSynth/maddenSynth.js, presentationIdFix/presentationIdFix.js, randomizeDraftClassEquipmentM24/randomizeDraftClassEquipmentM24.js, regenerateScheduleM24/regenerateScheduleM24.js, scheduleExtractorM24/scheduleExtractorM24.js, selectWeatherM24/selectWeatherM24.js, updatePlayersWithLookup/updatePlayersWithLookup.js
Updated several tools to use JSdoc comment format on functions and new get table object function.
=> Documentation update + new tables object method

presentationIdFix/presentationIdFix.js, randomizeDraftClassEquipmentM24/randomizeDraftClassEquipmentM24.js
Presentation ID Fix:
- Small updates to be ready for M25
Draft Class Equipment Randomizer:
- Added new JSON strategy logic to account for no player table equipment columns in M25, will now copy equipment data directly from visuals JSON rather than player table
- Updated header message for M25
=> Presentation ID Fix & Draft Class Equipment Randomizer - Updates for M25

presentationIdFix/presentationIdFix.js, selectWeather/buildExe.bat, selectWeather/selectWeather.js, selectWeatherM24/buildExe.bat, sixTeamPlayoff/buildExe.bat, sixTeamPlayoff/sixTeamPlayoff.js, sixTeamPlayoffM24/buildExe.bat, updatePlayersWithLookup/updatePlayersWithLookup.js
Updated the presentation ID fix, six team playoff, select weather, and update players with lookup tool for M25. Tools have been renamed accordingly.
Updated the method used for the six team playoff converter to ensure the 7 seed doesn't advance in some situations.
=> Updated several tools for M25 + other tweaks

selectWeather/selectWeather.js
- Fixed issue where snow games set using the weather selector would have weird, sunny-like lighting by adding a conditional value for snow game values to set precipitation to Medium for M25 and newer.
=> Weather Selector - Fixed snow game lighting issue

Utils/FranchiseTableId.js, presentationIdFix/presentationIdFix.js
Added new fingerprint table for M25 onwards since FranchiseDebugModule has been claimed.
Updated presentation ID fix tool to use new table for fingerprinting.
=> Added new fingerprint table

stringInternReader/buildExe.bat, stringInternReader/stringInternReader.js
Added new tool to read the franchise-string-intern.BIN file from Madden 25. It will convert it to a JSON with ushorts as the key and the string as the value.
=> Added string intern reader

emptyReferenceCheck/buildExe.bat, emptyReferenceCheck/emptyReferenceCheck.js, retroSchedules/transferRetroSchedule.js
- Updated retro schedule tool for M25
- Added empty reference check program
=> Multiple changes

isonParser/isonFunctions.js
Added functions to get and set ISON <-> JSON data from CharacterVisuals table.
=> Added ISON handling functions

isonParser/isonFunctions.js, isonParser/isonParser.js
Fixed an issue where the non-interned string type was being written to ISON twice.
=> ISON Functions - Fixed issue with writing non-interned strings to ISON

isonParser/isonFunctions.js
Fixed case on Uint32 write function call for ISON functions.
=> ISON Functions - Fixed Uint32 function call

bodyTypeFix/bodyTypeFix.js, bodyTypeFix/buildExe.bat
Added tool that updates CharacterBodyType for all players based on EA's body type approximation formula.
=> Added body type fix tool

bodyTypeFix/bodyTypeFix.js
Added an override if the visuals entry for a player has a bodyType key.
=> Body Type Fix - Added override if visuals has bodyType

bodyTypeFix/bodyTypeFix.js
=> Body Type Fix - Updated bodyTypeMap

isonParser/buildExe.bat
Added the schema include to the build script.
=> ISON Parser - Fixed schema include in build script

franchiseDataTransfer/25/franchiseDataTransfer.js
- Added option for express/customized mode when transferring. Express mode automatically selects the option that is most likely to work, while customized allows the user to pick every option.
- Fixed a couple option messages that did not mention to enter yes or no
=> Franchise Data Transfer - Added express/customized mode

isonParser/isonFunctions.js, isonParser/isonParser.js
Added a feature to dump the raw ISON entry.
=> ISON Parser - Added raw ISON dump feature

Utils/FranchiseUtils.js, Utils/ScheduleFunctions.js, isonParser/isonFunctions.js, presentationIdFix/presentationIdFix.js, randomizeDraftClassEquipment/randomizeDraftClassEquipment.js, sixTeamPlayoff/sixTeamPlayoff.js
Added two new things to FranchiseUtils:
- Constant that can be used to check if a script is running via nexe or direct node, useful for debug asserts
- Function to combine elements of an array into grammatically correct list string
Implemented the list string into a few tools and added debug asserts to a couple tools as well.
=> Added debug const and list format function

Utils/FranchiseUtils.js, maddenSynth/maddenSynth.js
- Added initial M25 support for MaddenSynth
- Adjusted the format list string function in FranchiseUtils to better handle lists with more than two elements.
=> MaddenSynth - Initial M25 support

shuffleCoachWardrobe/buildExe.bat, shuffleCoachWardrobe/lookupFiles/coachTopLookup.json, shuffleCoachWardrobe/lookupFiles/overrideTopLookup.json, shuffleCoachWardrobe/shuffleCoachWardrobe.js
Added tool that shuffles coach tops.
=> Added coach wardrobe shuffle tool

isonParser/isonParser.js
- Allow for multiple actions in ISON parser until the user chooses to exit.
=> ISON Parser - Allow for multiple actions

teamTiebreakerCalculator/buildExe.bat, teamTiebreakerCalculator/teamTiebreakerCalculator.js
Added a tool that can calculate tiebreaker related info such as SOV and SOS.
=> Added teamTiebreakerCalculator

randomizeDraftClassEquipment/randomizeDraftClassEquipment.js
- Fixed an issue with async promises causing an error.
=> DC Equipment Randomizer - Fixed async promise issue

recalculateDraftOrder/buildExe.bat, recalculateDraftOrder/recalculateDraftOrder.js, teamTiebreakerCalculator/tiebreakerFunctions.js
Added tool that must be run during staff week to recalculate the draft order.
=> Added draft order recalculation tool

Utils/FranchiseUtils.js, bodyTypeFix/bodyTypeFix.js, bodyTypeFix/buildExe.bat, franchiseDataTransfer/25/franchiseDataTransfer.js, package-lock.json, package.json, transferDraftClass/transferDraftClass.js
- Updated madden-franchise to latest version
- Added a new generateBodyType function with a custom body type formula instead of using EA's. Updated the bodytypefix and transfer tools to account for this.
=> Body Type changes + madden-franchise update

bodyTypeFix/bodyTypeFix.js
Added option in bodytypefix to allow user to only update DC players
=> Added draft class only option for body type fix

playerAppearanceTransfer/buildExe.bat, playerAppearanceTransfer/playerAppearanceTransfer.js
Added an option to include draft class players when transferring visual data
=> Player Appearance Transfer

MicroUtilities/clearMyFranchiseFingerprint/buildExe.bat, MicroUtilities/clearMyFranchiseFingerprint/clearMyFranchiseFingerprint.js
- Added tool to clear MFT file ID
- Added new MicroUtilities folder for very small programs not worthy of a dedicated folder in the repo root
=> Added MFT ID clear tool and new MicroUtilities folder

salaryCapGenerator/buildExe.bat, salaryCapGenerator/salaryCapGenerator.js, seasonYearSetup/buildExe.bat, seasonYearSetup/seasonYearSetup.js
Cleaned up a few things in prime's tools for consistency with everything else.
=> Cleaned up some things for consistency

recalculateDraftOrder/recalculateDraftOrder.js, teamTiebreakerCalculator/tiebreakerFunctions.js
- Added more tiebreakers to draft order recalculation
- Rounded SOS and SOV to 3 decimal places to match IRL.
=> Draft Order Recalculation Fixes

Utils/FranchiseUtils.js
Updated selectFranchiseFileAsync to remove quotes from file paths just like the sync version does.
=> Update async select franchise file to remove quotes

MicroUtilities/table3RawFieldDumper/table3RawFieldDumper.js, Utils/FranchiseUtils.js, bodyTypeFix/bodyTypeFix.js, bodyTypeFix/buildExe.bat, bodyTypeFix/pkgConfig.json, package-lock.json, package.json
- Updated madden-franchise to latest version with full support for M26, including visuals
- Added enums and functions related to body types to FranchiseUtils
- Updated body type logic in FranchiseUtils to support the new lean body type for M26
- Updated bodyTypeFix to support M26
=> Updated bodyTypeFix for M26 + API update

updatePlayersWithLookup/buildExe.bat, updatePlayersWithLookup/buildExeCoach.bat, updatePlayersWithLookup/pkgConfig.json, updatePlayersWithLookup/updateCoachesWithLookup.js, updatePlayersWithLookup/updatePlayersWithLookup.js
- Updated the update players with lookup and update coaches with lookup tools to support M26
=> Update mass-update by lookup tool for M26

fixDraftClassBodyTypes/pkgConfig.json, playersToDraftClass/buildExe.bat, playersToDraftClass/pkgConfig.json, playersToDraftClass/playersToDraftClass.js
- Added support for M26 franchise files in playersToDraftClass
=> Added M26 support for playersToDraftClass
